let reslist = [
  {
    type: "restaurant",
    data: {
      id: "375041",
      name: "Andhra Gunpowder",
      cloudinaryImageId: "byilgyrcfz690ryoasww",
      locality: "6th Block",
      areaName: "Koramangala",
      costForTwo: "₹350 for two",
      cuisines: ["Andhra", "Biryani", "South Indian"],
      avgRating: 4.4,
      parentId: "10496",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 0.1,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    data: {
      id: "25620",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      locality: "Intermediate Ring Road",
      areaName: "Ejipura",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.2,
      parentId: "547",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 0.8,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    data: {
      id: "38634",
      name: "Third Wave Coffee",
      cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
      costForTwo: "₹400 for two",
      cuisines: ["Beverages", "Bakery", "Continental"],
      avgRating: 4.5,
    },
  },
  {
    data: {
      id: "29627",
      name: "BIB - Breakfast in the Box",
      cloudinaryImageId: "nbcpg5xk6ekrrngmkd0b",
      locality: "1st block",
      areaName: "Koramangala",
      costForTwo: "₹350 for two",
      cuisines: ["American", "Continental"],
      avgRating: 4.4,
    },
  },
  {
    data: {
      id: "506324",
      name: "Louis Burger",
      cloudinaryImageId: "19d3d352cc815b9d88b22617b41fa97b",
      costForTwo: "₹600 for two",
      cuisines: ["Burgers", "American", "Fast Food"],
      avgRating: 4.4,
    },
  },
  {
    data: {
      id: "407064",
      name: "Momo Zone - The Momo Company",
      cloudinaryImageId: "8c6d80411d9355da849a2e484bb1c7c1",
      costForTwo: "₹150 for two",
      cuisines: ["Chinese", "Tibetan", "Fast Food"],
      avgRating: 4.1,
    },
  },
  {
    data: {
      id: "444178",
      name: "Magnolia Bakery",
      cloudinaryImageId: "6f0945b8b18d9f4241dd1cd9a70e23d7",
      costForTwo: "₹500 for two",
      cuisines: ["Bakery", "Desserts", "Ice Cream"],
      avgRating: 4.6,
    },
  },
  {
    data: {
      id: "8736",
      name: "Krispy Kreme",
      cloudinaryImageId: "e5dc389530ea3cd431a8fc016f6ce695",
      locality: "100 Ft intermediate Ring Road",
      costForTwo: "₹170 for two",
      cuisines: ["Desserts", "Beverages"],
      avgRating: 4.4,
    },
  },
  {
    data: {
      id: "107443",
      name: "Lo! - Low Carb and Keto Foods",
      cloudinaryImageId: "o8t0w5gdlujpigauaflw",
      locality: "HSR Layout",
      costForTwo: "₹150 for two",
      cuisines: ["Healthy Food", "Keto", "Continental"],
      avgRating: 4.4,
    },
  },
  {
    data: {
      id: "263485",
      name: "Chaayos Chai+Snacks=Relax",
      costForTwo: "₹250 for two",
      cloudinaryImageId: "cace805a6ba74137571d0f7ac92302b1",
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      avgRating: 4.5,
    },
  },
  {
    data: {
      id: "241027",
      name: "Namaste",
      cloudinaryImageId: "dtcwa1rxdskp3crqvpr3",
      costForTwo: "₹100 for two",
      cuisines: [
        "South Indian",
        "Thalis",
        "Biryani",
        "Desserts",
        "Beverages",
        "Indian",
      ],
      avgRating: 4.2,
    },
  },
  {
    data: {
      id: "74444",
      name: "Samosa Party",
      cloudinaryImageId: "d8d4e708a41f011361c949d44990d5e0",
      costForTwo: "₹100 for two",
      cuisines: [
        "Fast Food",
        "Snacks",
        "Beverages",
        "Chaat",
        "North Indian",
        "Street Food",
        "Sweets",
        "Desserts",
        "Punjabi",
        "Bakery",
      ],
      avgRating: 4.4,
    },
  },
];

export default reslist;
